[project]
name = "evilangrysite"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "awscli>=1.44.7",
    "jinja2>=3.1.6",
    "watchdog>=6.0.0",
]
